### ISSUE TITLE
In file TotChapter4.d there are unconditional lines for Drizzt replicas, while he might not be in party.

### ISSUE THREAD

**Issue by abalabokhin** [RoxanneSHS/SandrahToT#6]
All the talk to Drizzt in the file checks that he is in the party, but the talk chain @121-@129 doesn't. It is intentional or a bug?

**Comment by RoxanneSHS** [comment]
Oh, yes, I think you are right. I always only tested this with a full party
including Drizzt.
This change should solve it
CHAIN
IF~NumTimesTalkedTo(0)~THEN ToMoand KhalResc0
@121
***@***.***
***@***.***
***@***.***
***@***.***
==ToDrizzt IF~InParty("ToDrizzt")~THEN @126
==ToAdon IF~!InParty("ToDrizzt")~THEN @126
***@***.***
==ToDrizztIF~InParty("ToDrizzt")~THEN @128
==ToAdon IF~!InParty("ToDrizzt")~THEN @220
***@***.***~Enemy()~EXIT

Changing tra to
@127  = ~Is not everyone we can rescue important, my friend?~ (GENERIC,
replace Drizzt with my friend
@128  = ~If you put it this way. I may not always understand surfacer's
ways yet.~
@220  = ~If you put it this way. I may not always understand a women's
ways.~  (NEW LINE)

**Comment by RoxanneSHS** [comment]
I pushed the change to github already.

**Comment by abalabokhin** [comment]
Great, thank you.
